// Copyright 2021 Axel Voitier (@Axel Voitier)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_MUSIC_MODE
#define LAYER_STATE_16BIT

#undef MATRIX_ROWS
#define MATRIX_ROWS 10
#undef MATRIX_COLS
#define MATRIX_COLS 5
#undef MATRIX_ROW_PINS
#define MATRIX_ROW_PINS { F7, B1, B3, B2, B6 }
#undef MATRIX_COL_PINS
#define MATRIX_COL_PINS { D4, C6, D7, E6, B4 }

#define LAYOUT_3x5_1x2u_2x1u( \
   L14, L13, L12, L11, L10,                     R10, R11, R12, R13, R14,  \
   L24, L23, L22, L21, L20,                     R20, R21, R22, R23, R24,  \
   L34, L33, L32, L31, L30,                     R30, R31, R32, R33, R34,  \
        L44, L43, L42,      L41, L40, R40, R41,      R42, R43, R44,       \
                                 L50, R50                                 \
) { \
   { L10, L11, L12, L13, L14 }, \
   { L20, L21, L22, L23, L24 }, \
   { L30, L31, L32, L33, L34 }, \
   { L40, L41, L42, L43, L44 }, \
   { L50, KC_NO, KC_NO, KC_NO, KC_NO }, \
   { R10, R11, R12, R13, R14 }, \
   { R20, R21, R22, R23, R24 }, \
   { R30, R31, R32, R33, R34 }, \
   { R40, R41, R42, R43, R44 }, \
   { R50, KC_NO, KC_NO, KC_NO, KC_NO } \
}

#define UNICODE_SELECTED_MODES UC_LNX

#define ENCODERS_PAD_A { B5, B5 }
#define ENCODERS_PAD_B { F4, F5 }

#define RGB_DI_PIN D3
// #define DRIVER_LED_TOTAL 73

#ifdef RGB_MATRIX_ENABLE
#    define RGBLED_NUM       66 // Number of LEDs
#    define DRIVER_LED_TOTAL RGBLED_NUM
#    define RGB_MATRIX_SPLIT { 33, 33 }
#    define SPLIT_TRANSPORT_MIRROR
#    define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120

    #define RGB_DISABLE_WHEN_USB_SUSPENDED
    #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120
    #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR
    // #define ENABLE_RGB_MATRIX_ALPHAS_MODS
    // #define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
    // #define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
    // #define ENABLE_RGB_MATRIX_BREATHING
    #define ENABLE_RGB_MATRIX_BAND_SAT
    #define ENABLE_RGB_MATRIX_BAND_VAL
    // #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
    // #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
    // #define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
    // #define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
    // #define ENABLE_RGB_MATRIX_CYCLE_ALL
    // #define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
    // #define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
    // #define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
    // #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
    // #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
    // #define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
    // #define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
    // #define ENABLE_RGB_MATRIX_DUAL_BEACON
    // #define ENABLE_RGB_MATRIX_RAINBOW_BEACON
    // #define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
    // #define ENABLE_RGB_MATRIX_RAINDROPS
    // #define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
    // #define ENABLE_RGB_MATRIX_HUE_BREATHING
    // #define ENABLE_RGB_MATRIX_HUE_PENDULUM
    // #define ENABLE_RGB_MATRIX_HUE_WAVE
    // #define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
    // #define ENABLE_RGB_MATRIX_PIXEL_RAIN

    // #define RGB_MATRIX_FRAMEBUFFER_EFFECTS
    // #define ENABLE_RGB_MATRIX_TYPING_HEATMAP
    // #define ENABLE_RGB_MATRIX_DIGITAL_RAIN

    #define RGB_MATRIX_KEYPRESSES
    // #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
    // #define ENABLE_RGB_MATRIX_SOLID_REACTIVE
    // #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
    #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
    // #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
    // #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
    // #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
    #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
    // #define ENABLE_RGB_MATRIX_SPLASH
    #define ENABLE_RGB_MATRIX_MULTISPLASH
    // #define ENABLE_RGB_MATRIX_SOLID_SPLASH
    #define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#endif

#ifdef OLED_ENABLE
    #define SPLIT_LAYER_STATE_ENABLE
    #define SPLIT_MODS_ENABLE
#endif

// https://docs.qmk.fm/#/tap_hold
#undef TAPPING_TERM
#define TAPPING_TERM 250
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
// #define TAPPING_FORCE_HOLD

#define NO_AUTO_SHIFT_ALPHA
#define AUTO_SHIFT_TIMEOUT TAPPING_TERM
#define AUTO_SHIFT_NO_SETUP
#define AUTO_SHIT_REPEAT

#define QMK_KEYS_PER_SCAN 4

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY          0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL       16
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY    0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED      6
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX    64

#define OLED_TIMEOUT 15000

// #define MASTER_RIGHT
