# MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no

UNICODE_ENABLE = yes
ENCODER_ENABLE = yes
# AUTO_SHIFT_ENABLE = yes

# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = pimoroni_trackball

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812

TAP_DANCE_ENABLE = yes
