name: Build Lotus Firmware

on:
  push:
    branches:
    - master
    - develop
    - lotus

jobs:
  lotus-build:
    runs-on: ubuntu-latest

    container: qmkfm/qmk_cli

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: pip3 install -r requirements-dev.txt

    - name: Lint lotus
      run: qmk lint -kb lotus

    - name: Build Lotus ANSI variant
      run: qmk compile -kb lotus -km 78_ansi

    - name: Build Lotus ISO variant
      run: qmk compile -kb lotus -km 79_iso

    - name: Build Lotus JIS variant
      run: qmk compile -kb lotus -km 83_jis

#  tests:
#    runs-on: ubuntu-latest
#
#    container: qmkfm/qmk_cli
#
#    steps:
#    - uses: actions/checkout@v3
#      with:
#        submodules: recursive
#
#    - name: Install dependencies
#      run: pip3 install -r requirements-dev.txt
#
#    - name: Run tests
#      run: make test:all
